export const CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'image', label: 'Image' },
  { id: 'pdf', label: 'PDF' },
  { id: 'text', label: 'Text & Code' },
  { id: 'generator', label: 'Generator' },
  { id: 'time', label: 'Time' },
  { id: 'productivity', label: 'Productivity' },
  { id: 'web', label: 'Web' },
]

const repo = (name) => `https://github.com/berkinyilmaz/${name}`

export const PROJECTS = [
  {
    id: 'pomodoro-app',
    day: 30,
    name: 'Pomodoro Timer',
    blurb: 'Focus in 25-minute sprints with built-in breaks and gentle alerts.',
    category: 'productivity',
    demo: 'https://pomodoro-app-fawn-theta.vercel.app',
    repo: repo('pomodoro-app'),
    isNew: true,
  },
  {
    id: 'bg-remover',
    day: 1,
    name: 'Background Remover',
    blurb: 'Drop an image, get a clean PNG. No signup, no watermarks.',
    category: 'image',
    demo: 'https://bg-remover-wheat-eight.vercel.app',
    repo: repo('bg-remover'),
  },
  {
    id: 'image-compressor',
    day: 2,
    name: 'Image Compressor',
    blurb: 'Shrink JPG, PNG and WebP files without losing visible quality.',
    category: 'image',
    demo: 'https://image-compressor-zeta-drab.vercel.app',
    repo: repo('Image-Compressor'),
  },
  {
    id: 'image-converter',
    day: 3,
    name: 'Image Converter',
    blurb: 'Convert between JPG, PNG, WebP and AVIF in your browser.',
    category: 'image',
    demo: 'https://image-converter-zeta-woad.vercel.app',
    repo: repo('image-converter'),
  },
  {
    id: 'color-palette-extractor',
    day: 4,
    name: 'Color Palette Extractor',
    blurb: 'Upload an image and pull the dominant color palette in one click.',
    category: 'image',
    demo: 'https://color-palette-extractor-eight.vercel.app',
    repo: repo('color-palette-extractor'),
  },
  {
    id: 'color-harmony',
    day: 5,
    name: 'Color Harmony',
    blurb: 'Generate complementary, triadic and analogous palettes from any hue.',
    category: 'image',
    demo: 'https://color-harmony-five.vercel.app',
    repo: repo('color-harmony'),
  },
  {
    id: 'pdf-merger',
    day: 6,
    name: 'PDF Merger',
    blurb: 'Combine multiple PDFs into a single file, locally in your browser.',
    category: 'pdf',
    demo: 'https://pdf-merger-psi-beryl.vercel.app',
    repo: repo('PDF-Merger'),
  },
  {
    id: 'pdf-splitter',
    day: 7,
    name: 'PDF Splitter',
    blurb: 'Split a PDF into individual pages or custom ranges.',
    category: 'pdf',
    demo: 'https://pdf-splitter-iota.vercel.app',
    repo: repo('pdf-splitter'),
  },
  {
    id: 'shrink',
    day: 8,
    name: 'Shrink · PDF Compressor',
    blurb: 'Compress heavy PDFs so they fit in email and chat attachments.',
    category: 'pdf',
    demo: 'https://pdf-compressor-nine.vercel.app',
    repo: repo('pdf-compressor'),
  },
  {
    id: 'text-to-pdf',
    day: 9,
    name: 'Text → PDF',
    blurb: 'Type or paste text and export a clean, printable PDF.',
    category: 'pdf',
    demo: 'https://text-to-pdf-one.vercel.app',
    repo: repo('text-to-pdf'),
  },
  {
    id: 'json-formatter',
    day: 10,
    name: 'JSON Formatter',
    blurb: 'Format, minify and validate JSON with instant error feedback.',
    category: 'text',
    demo: 'https://json-formatter-amber.vercel.app',
    repo: repo('json-formatter'),
  },
  {
    id: 'markdown-preview',
    day: 11,
    name: 'Markdown Preview',
    blurb: 'Live side-by-side Markdown editor and preview pane.',
    category: 'text',
    demo: 'https://markdown-preview-taupe.vercel.app',
    repo: repo('markdown-preview'),
  },
  {
    id: 'text-cleaner',
    day: 12,
    name: 'Text Cleaner',
    blurb: 'Strip line breaks, extra spaces and weird Unicode in one paste.',
    category: 'text',
    demo: 'https://text-cleaner-orpin.vercel.app',
    repo: repo('text-cleaner'),
  },
  {
    id: 'text-to-image',
    day: 13,
    name: 'Text → Image',
    blurb: 'Turn a snippet of text into a sharable, social-ready image.',
    category: 'text',
    demo: 'https://text-to-img-theta.vercel.app',
    repo: repo('text-to-img'),
  },
  {
    id: 'password-generator',
    day: 14,
    name: 'Password Generator',
    blurb: 'Generate strong, customizable passwords with a strength meter.',
    category: 'generator',
    demo: 'https://password-generator-seven-zeta.vercel.app',
    repo: repo('password-generator'),
  },
  {
    id: 'qr-generator',
    day: 15,
    name: 'QR Generator',
    blurb: 'Create a downloadable QR code from any URL or text.',
    category: 'generator',
    demo: 'https://qrgenerator-liard.vercel.app',
    repo: repo('qr-generator'),
  },
  {
    id: 'nickname-generator',
    day: 16,
    name: 'Nickname Generator',
    blurb: 'Spin gamer-style nicknames with adjustable vibe and length.',
    category: 'generator',
    demo: 'https://nickname-generator-kappa.vercel.app',
    repo: repo('nickname-generator'),
  },
  {
    id: 'random-data-generator',
    day: 17,
    name: 'Random Data Generator',
    blurb: 'Fake names, emails, addresses and numbers for testing — instantly.',
    category: 'generator',
    demo: 'https://random-data-generator-gamma.vercel.app',
    repo: repo('random-data-generator'),
  },
  {
    id: 'internet-persona-generator',
    day: 18,
    name: 'Internet Persona Generator',
    blurb: 'A playful persona generator that paints a picture of your online self.',
    category: 'generator',
    demo: 'https://internet-persona-generator.vercel.app',
    repo: repo('internet-persona-generator'),
  },
  {
    id: 'timestamp-converter',
    day: 19,
    name: 'Timestamp Converter',
    blurb: 'UNIX ↔ human-readable date with 12 timezones and live clock.',
    category: 'time',
    demo: 'https://timestamp-converter-xi.vercel.app',
    repo: repo('timestamp-converter'),
  },
  {
    id: 'timezone-converter',
    day: 20,
    name: 'Timezone Converter',
    blurb: 'Compare any time across multiple cities at a glance.',
    category: 'time',
    demo: 'https://time-converter-eta.vercel.app',
    repo: repo('time-converter'),
  },
  {
    id: 'time-waste-calculator',
    day: 21,
    name: 'Time Waste Calculator',
    blurb: 'See how much of your life you spend on a habit — over a lifetime.',
    category: 'time',
    demo: 'https://time-waste-calculator.vercel.app',
    repo: repo('time-waste-calculator'),
  },
  {
    id: 'habits',
    day: 22,
    name: 'Habit Tracker',
    blurb: 'Track daily habits with streaks and a minimal calendar view.',
    category: 'productivity',
    demo: 'https://habits-tracker-app.vercel.app',
    repo: repo('habit-tracker'),
  },
  {
    id: 'mini-life-dashboard',
    day: 23,
    name: 'Mini Life Dashboard',
    blurb: 'A calm daily snapshot — time, weather, focus and intentions.',
    category: 'productivity',
    demo: 'https://mini-life-dashboard.vercel.app',
    repo: repo('mini-life-dashboard'),
  },
  {
    id: 'second-brain',
    day: 24,
    name: 'Second Brain',
    blurb: 'Capture notes and ideas in a single, instant-search inbox.',
    category: 'productivity',
    demo: 'https://second-brain-three-ashy.vercel.app',
    repo: repo('second-brain'),
  },
  {
    id: 'subscription-calculator',
    day: 25,
    name: 'Subscription Calculator',
    blurb: 'Add up your monthly subscriptions and see the real yearly cost.',
    category: 'productivity',
    demo: 'https://subscription-calculator-silk.vercel.app',
    repo: repo('Subscription-Calculator'),
  },
  {
    id: 'decision-maker',
    day: 26,
    name: 'Decision Maker',
    blurb: 'Stuck on a choice? Drop options in and let the wheel decide.',
    category: 'productivity',
    demo: 'https://decision-maker-seven-phi.vercel.app',
    repo: repo('decision-maker'),
  },
  {
    id: 'bio-page',
    day: 27,
    name: 'Bio Page',
    blurb: 'A minimal Linktree-style bio page you can publish in minutes.',
    category: 'web',
    demo: 'https://bio-page-hazel.vercel.app',
    repo: repo('bio-page'),
  },
  {
    id: 'link-preview',
    day: 28,
    name: 'Link Preview',
    blurb: 'Inspect Open Graph metadata for any URL — title, image, description.',
    category: 'web',
    demo: 'https://link-preview-weld-phi.vercel.app',
    repo: repo('link-preview'),
  },
  {
    id: 'url-shortener',
    day: 29,
    name: 'URL Shortener',
    blurb: 'Paste a long URL and get a short, shareable link.',
    category: 'web',
    demo: 'https://url-shortener-lyart-sigma.vercel.app',
    repo: repo('url-shortener'),
  },
]
